// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVfAPClordELvdhA7bU7e8YyXbZTiqhBU',
    appId: '1:601789230308:web:5925df43cd73d267cf10f1',
    messagingSenderId: '601789230308',
    projectId: 'flutter-firebase-2eb48',
    authDomain: 'flutter-firebase-2eb48.firebaseapp.com',
    storageBucket: 'flutter-firebase-2eb48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAqmgnWkUVxE1xG_zh5QVvC7PoJfRySQs',
    appId: '1:601789230308:android:3043e75e55e87553cf10f1',
    messagingSenderId: '601789230308',
    projectId: 'flutter-firebase-2eb48',
    storageBucket: 'flutter-firebase-2eb48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjlTwTj4FnhHrnUK8-hui0w_79A8fdyk',
    appId: '1:601789230308:ios:205c0d0e2750f108cf10f1',
    messagingSenderId: '601789230308',
    projectId: 'flutter-firebase-2eb48',
    storageBucket: 'flutter-firebase-2eb48.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjlTwTj4FnhHrnUK8-hui0w_79A8fdyk',
    appId: '1:601789230308:ios:205c0d0e2750f108cf10f1',
    messagingSenderId: '601789230308',
    projectId: 'flutter-firebase-2eb48',
    storageBucket: 'flutter-firebase-2eb48.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVfAPClordELvdhA7bU7e8YyXbZTiqhBU',
    appId: '1:601789230308:web:d89d7bb7018586a2cf10f1',
    messagingSenderId: '601789230308',
    projectId: 'flutter-firebase-2eb48',
    authDomain: 'flutter-firebase-2eb48.firebaseapp.com',
    storageBucket: 'flutter-firebase-2eb48.firebasestorage.app',
  );
}
